apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: iris-ml-cron-pipeline-
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: "Allow"
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

  # ---- WORKFLOW SPEC ----
  workflowSpec:
    entrypoint: ml-pipeline

    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

    templates:

    # DAG PIPELINE
    - name: ml-pipeline
      dag:
        tasks:
        - name: preprocess-data
          template: preprocess
        - name: train-model
          template: train
          dependencies: [preprocess-data]
        - name: evaluate-model
          template: evaluate
          dependencies: [train-model]

    # PREPROCESS
    - name: preprocess
      container:
        image: python:3.8-slim
        command: [bash, -c]
        args:
          - |
            pip install pandas scikit-learn
            python - <<EOF
            import pandas as pd
            from sklearn.datasets import load_iris

            iris = load_iris()
            df = pd.DataFrame(iris.data, columns=iris.feature_names)
            df['target'] = iris.target

            df.to_csv('/mnt/data/iris_prepared.csv', index=False)
            print("Iris dataset preprocessing completed.")
            EOF
        volumeMounts:
        - name: data
          mountPath: /mnt/data

    # TRAIN
    - name: train
      container:
        image: python:3.8-slim
        command: [bash, -c]
        args:
          - |
            pip install pandas scikit-learn joblib
            python - <<EOF
            import pandas as pd
            from sklearn.model_selection import train_test_split
            from sklearn.ensemble import RandomForestClassifier
            import joblib

            df = pd.read_csv('/mnt/data/iris_prepared.csv')
            X = df.drop('target', axis=1)
            y = df['target']

            X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=0.2, random_state=42)

            model = RandomForestClassifier(n_estimators=100, random_state=42)
            model.fit(X_train, y_train)

            joblib.dump(model, '/mnt/data/iris_model.joblib')
            print("Model training completed.")
            EOF
        volumeMounts:
        - name: data
          mountPath: /mnt/data

    # EVALUATE
    - name: evaluate
      container:
        image: python:3.8-slim
        command: [bash, -c]
        args:
          - |
            pip install pandas scikit-learn joblib
            python - <<EOF
            import pandas as pd
            from sklearn.metrics import accuracy_score
            import joblib

            df = pd.read_csv('/mnt/data/iris_prepared.csv')
            X = df.drop('target', axis=1)
            y = df['target']
            model = joblib.load('/mnt/data/iris_model.joblib')

            y_pred = model.predict(X)
            accuracy = accuracy_score(y, y_pred)

            print("Model Evaluation Results:")
            print(f"Accuracy: {accuracy}")

            with open('/mnt/data/evaluation_results.txt', "w") as f:
                f.write(f"Accuracy: {accuracy}\n")
            EOF
        volumeMounts:
        - name: data
          mountPath: /mnt/data
